name: Build via msbuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    name: Build via msbuild
    steps:

      # Fetch the latest code and setup msbuild
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2.0.0
        
      - name: Build app for release
        run: msbuild CardMacro\CardMacro.vcxproj -t:rebuild -property:Configuration=Release